spring.application.name=transactions

# Enable automatic schema execution
spring.sql.init.mode=always

# Spring Batch configuration
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

# Default path (can be overridden by command line)
file.input.path=transactions.csv


